title: "SkillNorth"
description: "Find the skills. Build your future."

lang: en

url: "https://nausica-20.github.io"
baseurl: "/SkillNorth"

permalink: pretty

markdown: kramdown

timezone: Europe/Rome
